"""estructura inicial safecity

Revision ID: 5000efa42e6b
Revises: 
Create Date: 2026-06-15 11:56:22.440919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5000efa42e6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_evidencia',
    sa.Column('id_tipo_evidencia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_evidencia')
    )
    op.create_table('zonas',
    sa.Column('id_zona', sa.Integer(), nullable=False),
    sa.Column('nombre_zona', sa.String(length=100), nullable=False),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_zona')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('reportes',
    sa.Column('id_reporte', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reporte')
    )
    op.create_table('evidencias',
    sa.Column('id_evidencia', sa.Integer(), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('id_reporte', sa.Integer(), nullable=True),
    sa.Column('id_tipo_evidencia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_reporte'], ['reportes.id_reporte'], ),
    sa.ForeignKeyConstraint(['id_tipo_evidencia'], ['tipos_evidencia.id_tipo_evidencia'], ),
    sa.PrimaryKeyConstraint('id_evidencia')
    )
    op.create_table('reporte_zona',
    sa.Column('id_reporte_zona', sa.Integer(), nullable=False),
    sa.Column('id_reporte', sa.Integer(), nullable=True),
    sa.Column('id_zona', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_reporte'], ['reportes.id_reporte'], ),
    sa.ForeignKeyConstraint(['id_zona'], ['zonas.id_zona'], ),
    sa.PrimaryKeyConstraint('id_reporte_zona')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporte_zona')
    op.drop_table('evidencias')
    op.drop_table('reportes')
    op.drop_table('usuarios')
    op.drop_table('zonas')
    op.drop_table('tipos_evidencia')
    op.drop_table('roles')
    op.drop_table('categorias')
    # ### end Alembic commands ###
